"""Add user_id to dynamic_tables

Revision ID: 46ef1241b28e
Revises: 70217ecbee46
Create Date: 2026-02-13 18:56:19.496779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46ef1241b28e'
down_revision: Union[str, Sequence[str], None] = '70217ecbee46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dynamic_tables', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index('idx_dynamic_table_user', 'dynamic_tables', ['user_id'], unique=False)
    op.create_index(op.f('ix_dynamic_tables_user_id'), 'dynamic_tables', ['user_id'], unique=False)
    op.create_foreign_key(None, 'dynamic_tables', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dynamic_tables', type_='foreignkey')
    op.drop_index(op.f('ix_dynamic_tables_user_id'), table_name='dynamic_tables')
    op.drop_index('idx_dynamic_table_user', table_name='dynamic_tables')
    op.drop_column('dynamic_tables', 'user_id')
    # ### end Alembic commands ###
