"""Update User model for auth

Revision ID: 70217ecbee46
Revises: ab4ffea2e8b1
Create Date: 2026-02-12 11:55:23.118676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70217ecbee46'
down_revision: Union[str, Sequence[str], None] = 'ab4ffea2e8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placement_committee_-_personal_details_of_students')
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Unique user identifier',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="User's email address (unique)",
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Account creation timestamp',
               existing_nullable=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Full name of the user'))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Account creation timestamp',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment="User's email address (unique)",
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='Unique user identifier',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'username')
    op.create_table('placement_committee_-_personal_details_of_students',
    sa.Column('COMMUNITY_AREA_NUMBER', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('COMMUNITY_AREA_NAME', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('PERCENT_OF_HOUSING_CROWDED', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PERCENT_HOUSEHOLDS_BELOW_POVERTY', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PERCENT_AGED_16__UNEMPLOYED', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PERCENT_AGED_UNDER_18_OR_OVER_64', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PER_CAPITA_INCOME', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('HARDSHIP_INDEX', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
