"""Enhanced schema

Revision ID: ab4ffea2e8b1
Revises: e182a2fdb05b
Create Date: 2026-02-12 10:48:27.581213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab4ffea2e8b1'
down_revision: Union[str, Sequence[str], None] = 'e182a2fdb05b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynamic_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False, comment='Name of the dynamically created table'),
    sa.Column('original_filename', sa.String(), nullable=True, comment='Original uploaded file name'),
    sa.Column('columns_info', sa.Text(), nullable=True, comment='JSON string describing column names and types'),
    sa.Column('row_count', sa.Integer(), nullable=True, comment='Number of rows in the table'),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True, comment='Upload timestamp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_name')
    )
    op.create_index('idx_dynamic_table_name', 'dynamic_tables', ['table_name'], unique=False)
    op.create_index(op.f('ix_dynamic_tables_id'), 'dynamic_tables', ['id'], unique=False)
    op.drop_table('patients')
    op.add_column('orders', sa.Column('product_id', sa.Integer(), nullable=True, comment='References products.id'))
    op.add_column('orders', sa.Column('quantity', sa.Integer(), nullable=True, comment='Number of items ordered'))
    op.alter_column('orders', 'id',
               existing_type=sa.INTEGER(),
               comment='Unique order identifier',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='References users.id')
    op.alter_column('orders', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Total order amount in USD',
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               comment='Order status: pending, completed, cancelled',
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Order creation timestamp',
               existing_nullable=True)
    op.create_index('idx_order_created', 'orders', ['created_at'], unique=False)
    op.create_index('idx_order_status', 'orders', ['status'], unique=False)
    op.create_index('idx_order_user', 'orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['id'])
    op.add_column('products', sa.Column('category', sa.String(), nullable=True, comment='Product category (electronics, clothing, etc)'))
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True, comment='Product description'))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True, comment='Product listing timestamp'))
    op.alter_column('products', 'id',
               existing_type=sa.INTEGER(),
               comment='Unique product identifier',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               comment='Product name',
               existing_nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Product price in USD',
               existing_nullable=False)
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               comment='Current stock quantity',
               existing_nullable=True)
    op.create_index('idx_product_category', 'products', ['category'], unique=False)
    op.create_index('idx_product_name', 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='Unique user identifier',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               comment='Full name of the user',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment="User's email address (unique)",
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Account creation timestamp',
               existing_nullable=True)
    op.create_index('idx_user_created', 'users', ['created_at'], unique=False)
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_user_created', table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Account creation timestamp',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="User's email address (unique)",
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Full name of the user',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Unique user identifier',
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index('idx_product_name', table_name='products')
    op.drop_index('idx_product_category', table_name='products')
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Current stock quantity',
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Product price in USD',
               existing_nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Product name',
               existing_nullable=False)
    op.alter_column('products', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Unique product identifier',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'description')
    op.drop_column('products', 'category')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index('idx_order_user', table_name='orders')
    op.drop_index('idx_order_status', table_name='orders')
    op.drop_index('idx_order_created', table_name='orders')
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Order creation timestamp',
               existing_nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Order status: pending, completed, cancelled',
               existing_nullable=True)
    op.alter_column('orders', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Total order amount in USD',
               existing_nullable=False)
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='References users.id')
    op.alter_column('orders', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Unique order identifier',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('orders', 'quantity')
    op.drop_column('orders', 'product_id')
    op.create_table('patients',
    sa.Column('P001', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('John', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Doe', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('123456789', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('1990-05-15', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('M', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('123 Main St', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('D001', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_dynamic_tables_id'), table_name='dynamic_tables')
    op.drop_index('idx_dynamic_table_name', table_name='dynamic_tables')
    op.drop_table('dynamic_tables')
    # ### end Alembic commands ###
